### ISSUE TITLE
Could you please provide ActivityNet feature?

### ISSUE THREAD

**Issue by mitming** [zhang-can/CoLA#2]
Hi, could you please provide the extracted features for ActivityNet?

**Comment by zhang-can** [comment]
Hi @mitming, ActivityNet v1.2 features have been sent to you via e-mail :)

**Comment by tangyuelm** [comment]
> Hi, could you please provide the extracted features for ActivityNet?

Hi @mitming , did you receive the extracted features and .conf file for the ActivityNet dataset? I sent the request in another issue but the author @zhang-can has not responded to me. If possible, could you also send me a copy of the features and .conf file to my e-mail which is YUT51@pitt.edu? 

Thank you very much.
Yue
