### ISSUE TITLE
Number of Training Epoch and Time

### ISSUE THREAD

**Issue by HenryPengZou** [zhang-can/CoLA#5]
Thanks for your great work! 

I notice that the number of training epochs are 6k and 8k for the two datasets respectively. That's quite a big number. I wonder what is the reason that it takes so many epochs to train? Do you have an ablation study on the effect of training epochs? 

Besides, could you please provide your training times?

Thanks!

**Comment by zhang-can** [comment]
Hi @HenryPengZou 

Sorry to cause this confusion. The "epoch" actually refers to "iteration" in our code, please refer to [this config file](https://github.com/zhang-can/CoLA/blob/main/core/config.py#L13).

The training of CoLA is very fast. On a single NVIDIA GeForce GTX 1080 GPU, the whole training process takes less than 1 hour. 

Best wishes,
Can
