### ISSUE TITLE
Discrepancy between feature_fps and original_fps

### ISSUE THREAD

**Issue by JosephKKim** [zhang-can/CoLA#6]
Hi thanks for releasing your work.
I found myself having trouble relating the original video and extracted features.
In your code, cfg.FEATS_FPS = 25, and it seems like that original video has fps of 30.

From the paper, I can see that 1 snippet is consist of 16 frames, 
I understand that that's where t_factor formula in utils.py comes out.
-> t_factor = (16 * v_len) / (scale * num_segments * sampling_frames)

BUT when I run code for example for the test_video_000004,  it has 1,011 frames but the number of segments of the extracted feature is 52... (RGB feature size of 52 x 1024)

Can you please explain what is going on between feature extractor and your model?

**Comment by zhang-can** [comment]
Hi @JosephKKim ,

Sorry for the late reply.

The ``feature_fps'' is the frame extraction setting. For example, for the test_video_000004.mp4, the duration of this video is 33.82 sec, so we extracted total 33.82s * 25fps = 845 frames. Then we use the *16 non-overlapping setting* to extract the features from these 845 frames, thus 845/16=52 features are obtained.

Hope this can help you :)
